python train.py \
--logtostderr \
--training_number_of_steps=300 \
--train_split="train" \
--model_variant="xception_65" \
--atrous_rates=6 \
--atrous_rates=12 \
--atrous_rates=18 \
--output_stride=16 \
--decoder_output_stride=4 \
--train_crop_size=321,321 \
--train_batch_size=4 \
--dataset="camvid" \
--tf_initial_checkpoint='/Users/huanying/bai/models-master/research/deeplab/deeplabv3_cityscapes_train/model.ckpt' \
--train_logdir='/Users/huanying/bai/dataset/CamVid/exp/camvid_train/train' \
--dataset_dir='/Users/huanying/bai/dataset/CamVid/tfrecord'
